### ISSUE TITLE
Is vue-material dependency in a vue 3 project?

### ISSUE THREAD

**Issue by gakenge** [mikimoresi/vue3-material#1]
Hello, I'm curious on how to make this work in a vue 3 app as I can see vue-material is required.

**Comment by mikimoresi** [comment]
Hello gakenge,
This is a collection of compinents derived from vue material and converted to vue3, i wanted to embed them directly in my project so i did not used the common library npm pattern, no npm install is required.
All you need to do is to copy the folder and add in to your project then require components as you would normally do with your custom components.
If you see App.vue there are examples of how to use buttons, tooltips etc...

**Comment by gakenge** [comment]
Ah okay, makes sense. Thanks for the collection.
